export const ROUTES = {
  HOME: '/',
  EVENTS: '/events',
  EVENT_DETAIL: (slug: string) => `/events/${slug}`,
  CATEGORY: (slug: string) => `/category/${slug}`,
  CITY: (city: string) => `/city/${city}`,
  SEARCH: '/search',
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
  },
  MEMBERS: {
    DASHBOARD: '/members/dashboard',
    PROFILE: '/members/profile',
    BOOKINGS: '/members/bookings',
    NOTIFICATIONS: '/members/notifications',
    SAVED_EVENTS: '/members/saved-events',
    SETTINGS: '/members/settings/notifications',
  },
  HOST: {
    DASHBOARD: '/members/host-dashboard',
    CREATE_EVENT: '/members/host-dashboard/create-event',
    EVENTS: '/members/host-dashboard/events',
    EARNINGS: '/members/host-dashboard/earnings',
    PAYOUTS: '/members/host-dashboard/payouts',
    PROMO_CODES: '/members/host-dashboard/promo-codes',
    BECOME_HOST: '/members/become-host',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    ANALYTICS: '/admin/analytics',
    EVENTS: '/admin/events',
    USERS: '/admin/users',
    REPORTS: '/admin/reports',
    PAYOUTS: '/admin/payouts',
    AUDIT_LOGS: '/admin/audit-logs',
    FEATURED: '/admin/featured',
  },
};
