'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '../lib/supabase/server'
import {
  loginSchema,
  registerSchema,
  forgotPasswordSchema,
  resetPasswordSchema,
} from '../lib/validations/auth.schemas'

export async function loginAction(formData: FormData) {
  const data = Object.fromEntries(formData.entries())
  const parsed = loginSchema.safeParse(data)

  if (!parsed.success) {
    return { error: 'Invalid login details' }
  }

  const supabase = await createClient()

  const { error } = await supabase.auth.signInWithPassword({
    email: parsed.data.email,
    password: parsed.data.password,
  })

  if (error) {
    return { error: error.message }
  }

  revalidatePath('/')
  redirect('/members/dashboard')
}

export async function registerAction(formData: FormData) {
  const data = Object.fromEntries(formData.entries())
  const parsed = registerSchema.safeParse(data)

  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message || 'Invalid registration details' }
  }

  const { email, password, username } = parsed.data

  const supabase = await createClient()

  // 1. Check if username is unique
  const { data: existingUser, error: checkError } = await supabase
    .from('users')
    .select('id')
    .eq('username', username)
    .single()

  if (existingUser) {
    return { error: 'Username is already taken' }
  }
  
  if (checkError && checkError.code !== 'PGRST116') {
     // PGRST116 means no rows returned, which is what we want here
     return { error: 'Error checking username uniqueness' }
  }

  // 2. Sign up the user via Supabase Auth
  const { data: authData, error: authError } = await supabase.auth.signUp({
    email,
    password,
  })

  if (authError || !authData.user) {
    return { error: authError?.message || 'Failed to create account.' }
  }

  // 3. Generate anonymous_alias 
  // format: adjective+animal+4digitnumber
  const adjectives = ['Blue', 'Red', 'Quick', 'Happy', 'Clever', 'Brave', 'Wild', 'Calm']
  const animals = ['Fox', 'Bear', 'Wolf', 'Owl', 'Hawk', 'Lion', 'Tiger', 'Seal']
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)]
  const animal = animals[Math.floor(Math.random() * animals.length)]
  const num = Math.floor(1000 + Math.random() * 9000)
  const anonymous_alias = `${adj}${animal}${num}`

  // 4. Insert into our custom public.users table
  // @ts-expect-error Types generated by Supabase might have strict literal mismatches on generic inference here
  const { error: insertError } = await supabase.from('users').insert({
    id: authData.user.id,
    username,
    email,
    anonymous_alias,
    // Note: Other fields will default as per DB schema
  })

  if (insertError) {
    // Note: In a robust system, we would clean up the auth user here or use a DB trigger
    return { error: 'User account created but failed to initialize profile.' }
  }

  return { success: true }
}

export async function logoutAction() {
  const supabase = await createClient()
  await supabase.auth.signOut()
  redirect('/')
}

export async function forgotPasswordAction(formData: FormData) {
  const data = Object.fromEntries(formData.entries())
  const parsed = forgotPasswordSchema.safeParse(data)

  if (!parsed.success) {
    // Return early but keeping success: true simulates email exists for security
    return { success: true } 
  }

  const supabase = await createClient()

  // Note: For a real app, ensure NEXT_PUBLIC_SITE_URL is set for the redirectTo
  await supabase.auth.resetPasswordForEmail(parsed.data.email, {
    redirectTo: `${process.env.NEXT_PUBLIC_SITE_URL}/reset-password`,
  })

  // Never reveal if email exists or not
  return { success: true }
}

export async function updatePasswordAction(formData: FormData) {
  const data = Object.fromEntries(formData.entries())
  const parsed = resetPasswordSchema.safeParse(data)

  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message || 'Invalid password details' }
  }

  const supabase = await createClient()

  const { error } = await supabase.auth.updateUser({
    password: parsed.data.password,
  })

  if (error) {
    return { error: error.message }
  }

  return { success: true }
}

export async function checkUsernameAction(username: string) {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('users')
    .select('id')
    .eq('username', username)
    .single()

  if (data) {
    return { available: false }
  }
  return { available: true }
}
