'use server'

import { createClient } from '../lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createHostProfileSchema } from '../lib/validations/host.schemas'

export async function createHostProfileAction(formData: FormData) {
  const data = Object.fromEntries(formData.entries())
  const parsed = createHostProfileSchema.safeParse(data)

  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message || 'Invalid profile details' }
  }

  const supabase = await createClient()

  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { error: 'Unauthorized' }
  }

  // 1. Insert into host_profiles
  // @ts-expect-error Types generated by Supabase might have strict literal mismatches on generic inference here
  const { error: insertError } = await supabase.from('host_profiles').insert({
    user_id: user.id,
    host_type: parsed.data.host_type,
    display_name: parsed.data.display_name,
    tagline: parsed.data.tagline || null,
    description: parsed.data.description || null,
    website_url: parsed.data.website_url || null,
    instagram_handle: parsed.data.instagram_handle || null,
    // Form requirement step 3 fields:
    city: formData.get('city') as string || null,
    state: formData.get('state') as string || null,
    country: formData.get('country') as string || null,
    is_approved: false, // Wait for admin approval conceptually 
    kyc_status: 'pending',
  })

  if (insertError) {
    // Unique constraint on user_id will catch duplicates
    if (insertError.code === '23505') {
      return { error: 'You already have a host profile.' }
    }
    return { error: insertError.message }
  }

  // 2. Update users table role to 'host'
  const { error: roleError } = await (supabase
    .from('users')
    .update({ role: 'host' } as never)
    .eq('id', user.id) as unknown as Promise<{ error: any }>)

  if (roleError) {
    // If this fails, the profile was created but role wasn't updated. 
    // In a real app we'd want an RPC transaction, but we handle it gracefully here.
    return { error: 'Profile created but failed to update user role.' }
  }

  revalidatePath('/dashboard')
  revalidatePath('/become-host')
  redirect('/members/host-dashboard') // Will naturally bounce to pending logic initially
}
